name: 'Create Pull Request'
description: 'Create a pull request in an external repository'
inputs:
  github_token:
    description: 'GitHub token for API calls'
    required: true
  fork_owner:
    description: 'Fork owner username'
    required: true
  branch:
    description: 'Branch name to create PR from'
    required: true
  base_branch:
    description: 'Base branch name'
    required: true
  target_repo:
    description: 'Target repository (e.g., microsoft/winget-pkgs)'
    required: true
  title:
    description: 'PR title'
    required: true
  body:
    description: 'PR body'
    required: true
outputs:
  pr_url:
    description: 'URL of the created PR'
    value: ${{ steps.create_pr.outputs.pr_url }}
runs:
  using: 'composite'
  steps:
    - name: Create Pull Request
      id: create_pr
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        HEAD_BRANCH="${{ inputs.fork_owner }}:${{ inputs.branch }}"
        BASE_BRANCH="${{ inputs.base_branch }}"
        
        echo "Creating PR with:"
        echo "  Head: $HEAD_BRANCH"
        echo "  Base: $BASE_BRANCH"
        echo "  Title: ${{ inputs.title }}"
        
        # Create PR payload
        PR_PAYLOAD=$(jq -n \
          --arg title "${{ inputs.title }}" \
          --arg head "$HEAD_BRANCH" \
          --arg base "$BASE_BRANCH" \
          --arg body "${{ inputs.body }}" \
          '{title: $title, head: $head, base: $base, body: $body}')
        
        # Create PR using GitHub API
        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          "https://api.github.com/repos/${{ inputs.target_repo }}/pulls" \
          -d "$PR_PAYLOAD")
        
        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        BODY=$(echo "$RESPONSE" | sed '$d')
        
        echo "Response HTTP code: $HTTP_CODE"
        
        if [ "$HTTP_CODE" -eq 201 ]; then
          PR_URL=$(echo "$BODY" | jq -r '.html_url')
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
          echo "✅ Pull Request created successfully: $PR_URL"
        elif [ "$HTTP_CODE" -eq 422 ]; then
          echo "::warning::PR creation failed with validation error"
          echo "Response body:"
          echo "$BODY" | jq '.' || echo "$BODY"
          
          # Try to extract specific error messages
          ERRORS=$(echo "$BODY" | jq -r '.errors[]?.message // .message // "Unknown validation error"' 2>/dev/null || echo "Unknown error")
          echo "::warning::Error details: $ERRORS"
          
          # Check if PR already exists
          EXISTING_PR=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ inputs.target_repo }}/pulls?head=$HEAD_BRANCH&state=open" | jq -r '.[0].html_url // empty')
          
          if [ -n "$EXISTING_PR" ]; then
            echo "pr_url=$EXISTING_PR" >> $GITHUB_OUTPUT
            echo "::info::PR already exists: $EXISTING_PR"
          else
            echo "::warning::Branch was created: ${{ inputs.branch }}"
            echo "::warning::You can manually create PR at: https://github.com/${{ inputs.target_repo }}/compare/$BASE_BRANCH...$HEAD_BRANCH"
          fi
        else
          echo "::error::Failed to create PR. HTTP $HTTP_CODE"
          echo "Response body:"
          echo "$BODY" | jq '.' || echo "$BODY"
          exit 1
        fi
